// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdNtp6TTOcFsxeVHrT6pr6muIa3f1swE4',
    appId: '1:1031951201822:web:cddfa3b295fe8ead83200f',
    messagingSenderId: '1031951201822',
    projectId: 'cool-coffee-app',
    authDomain: 'cool-coffee-app.firebaseapp.com',
    storageBucket: 'cool-coffee-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuo9H8tKY_7ZxWu-kk6j05dgb5Q0biwIg',
    appId: '1:1031951201822:android:053405457b93b5c883200f',
    messagingSenderId: '1031951201822',
    projectId: 'cool-coffee-app',
    storageBucket: 'cool-coffee-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBySTjSeKLtraPM77RmdulQ0f4srvlqj-k',
    appId: '1:1031951201822:ios:5cac295dab64deca83200f',
    messagingSenderId: '1031951201822',
    projectId: 'cool-coffee-app',
    storageBucket: 'cool-coffee-app.appspot.com',
    iosClientId: '1031951201822-c28e903h04h67jik3098frbqqkhm5rh6.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBySTjSeKLtraPM77RmdulQ0f4srvlqj-k',
    appId: '1:1031951201822:ios:5cac295dab64deca83200f',
    messagingSenderId: '1031951201822',
    projectId: 'cool-coffee-app',
    storageBucket: 'cool-coffee-app.appspot.com',
    iosClientId: '1031951201822-c28e903h04h67jik3098frbqqkhm5rh6.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeeapp',
  );
}
